<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.4" tiledversion="1.4.2" name="Chunks" tilewidth="128" tileheight="128" tilecount="200" columns="20">
 <image source="chunks.tmx" width="2560" height="1280"/>
 <tile id="0" type="Chunk"/>
 <tile id="1" type="Chunk"/>
 <tile id="2" type="Chunk"/>
 <tile id="3" type="Chunk"/>
 <tile id="4" type="Chunk"/>
 <tile id="5" type="Chunk"/>
 <tile id="6" type="Chunk"/>
 <tile id="7" type="Chunk"/>
 <tile id="8" type="Chunk"/>
 <tile id="9" type="Chunk"/>
 <tile id="10" type="Chunk"/>
 <tile id="11" type="Chunk"/>
 <tile id="12" type="Chunk"/>
 <tile id="13" type="Chunk"/>
 <tile id="14" type="Chunk"/>
 <tile id="15" type="Chunk"/>
 <tile id="16" type="Chunk"/>
 <tile id="17" type="Chunk"/>
 <tile id="18" type="Chunk"/>
 <tile id="19" type="Chunk"/>
 <tile id="20" type="Chunk"/>
 <tile id="21" type="Chunk"/>
 <tile id="22" type="Chunk"/>
 <tile id="23" type="Chunk"/>
 <tile id="24" type="Chunk"/>
 <tile id="25" type="Chunk"/>
 <tile id="26" type="Chunk"/>
 <tile id="27" type="Chunk"/>
 <tile id="28" type="Chunk"/>
 <tile id="29" type="Chunk"/>
 <tile id="30" type="Chunk"/>
 <tile id="31" type="Chunk"/>
 <tile id="32" type="Chunk"/>
 <tile id="33" type="Chunk"/>
 <tile id="34" type="Chunk"/>
 <tile id="35" type="Chunk"/>
 <tile id="36" type="Chunk"/>
 <tile id="37" type="Chunk"/>
 <tile id="38" type="Chunk"/>
 <tile id="39" type="Chunk"/>
 <tile id="40" type="Chunk"/>
 <tile id="41" type="Chunk"/>
 <tile id="42" type="Chunk"/>
 <tile id="43" type="Chunk"/>
 <tile id="44" type="Chunk"/>
 <tile id="45" type="Chunk"/>
 <tile id="46" type="Chunk"/>
 <tile id="47" type="Chunk"/>
 <tile id="48" type="Chunk"/>
 <tile id="49" type="Chunk"/>
 <tile id="50" type="Chunk"/>
 <tile id="51" type="Chunk"/>
 <tile id="52" type="Chunk"/>
 <tile id="53" type="Chunk"/>
 <tile id="54" type="Chunk"/>
 <tile id="55" type="Chunk"/>
 <tile id="56" type="Chunk"/>
 <tile id="57" type="Chunk"/>
 <tile id="58" type="Chunk"/>
 <tile id="59" type="Chunk"/>
 <tile id="60" type="Chunk"/>
 <tile id="61" type="Chunk"/>
 <tile id="62" type="Chunk"/>
 <tile id="63" type="Chunk"/>
 <tile id="64" type="Chunk"/>
 <tile id="65" type="Chunk"/>
 <tile id="66" type="Chunk"/>
 <tile id="67" type="Chunk"/>
 <tile id="68" type="Chunk"/>
 <tile id="69" type="Chunk"/>
 <tile id="70" type="Chunk"/>
 <tile id="71" type="Chunk"/>
 <tile id="72" type="Chunk"/>
 <tile id="73" type="Chunk"/>
 <tile id="74" type="Chunk"/>
 <tile id="75" type="Chunk"/>
 <tile id="76" type="Chunk"/>
 <tile id="77" type="Chunk"/>
 <tile id="78" type="Chunk"/>
 <tile id="79" type="Chunk"/>
 <tile id="80" type="Chunk"/>
 <tile id="81" type="Chunk"/>
 <tile id="82" type="Chunk"/>
 <tile id="83" type="Chunk"/>
 <tile id="84" type="Chunk"/>
 <tile id="85" type="Chunk"/>
 <tile id="86" type="Chunk"/>
 <tile id="87" type="Chunk"/>
 <tile id="88" type="Chunk"/>
 <tile id="89" type="Chunk"/>
 <tile id="90" type="Chunk"/>
 <tile id="91" type="Chunk"/>
 <tile id="92" type="Chunk"/>
 <tile id="93" type="Chunk"/>
 <tile id="94" type="Chunk"/>
 <tile id="95" type="Chunk"/>
 <tile id="96" type="Chunk"/>
 <tile id="97" type="Chunk"/>
 <tile id="98" type="Chunk"/>
 <tile id="99" type="Chunk"/>
 <tile id="100" type="Chunk"/>
 <tile id="101" type="Chunk"/>
 <tile id="102" type="Chunk"/>
 <tile id="103" type="Chunk"/>
 <tile id="104" type="Chunk"/>
 <tile id="105" type="Chunk"/>
 <tile id="106" type="Chunk"/>
 <tile id="107" type="Chunk"/>
 <tile id="108" type="Chunk"/>
 <tile id="109" type="Chunk"/>
 <tile id="110" type="Chunk"/>
 <tile id="111" type="Chunk"/>
 <tile id="112" type="Chunk"/>
 <tile id="113" type="Chunk"/>
 <tile id="114" type="Chunk"/>
 <tile id="115" type="Chunk"/>
 <tile id="116" type="Chunk"/>
 <tile id="117" type="Chunk"/>
 <tile id="118" type="Chunk"/>
 <tile id="119" type="Chunk"/>
 <tile id="120" type="Chunk"/>
 <tile id="121" type="Chunk"/>
 <tile id="122" type="Chunk"/>
 <tile id="123" type="Chunk"/>
 <tile id="124" type="Chunk"/>
 <tile id="125" type="Chunk"/>
 <tile id="126" type="Chunk"/>
 <tile id="127" type="Chunk"/>
 <tile id="128" type="Chunk"/>
 <tile id="129" type="Chunk"/>
 <tile id="130" type="Chunk"/>
 <tile id="131" type="Chunk"/>
 <tile id="132" type="Chunk"/>
 <tile id="133" type="Chunk"/>
 <tile id="134" type="Chunk"/>
 <tile id="135" type="Chunk"/>
 <tile id="136" type="Chunk"/>
 <tile id="137" type="Chunk"/>
 <tile id="138" type="Chunk"/>
 <tile id="139" type="Chunk"/>
 <tile id="140" type="Chunk"/>
 <tile id="141" type="Chunk"/>
 <tile id="142" type="Chunk"/>
 <tile id="143" type="Chunk"/>
 <tile id="144" type="Chunk"/>
 <tile id="145" type="Chunk"/>
 <tile id="146" type="Chunk"/>
 <tile id="147" type="Chunk"/>
 <tile id="148" type="Chunk"/>
 <tile id="149" type="Chunk"/>
 <tile id="150" type="Chunk"/>
 <tile id="151" type="Chunk"/>
 <tile id="152" type="Chunk"/>
 <tile id="153" type="Chunk"/>
 <tile id="154" type="Chunk"/>
 <tile id="155" type="Chunk"/>
 <tile id="156" type="Chunk"/>
 <tile id="157" type="Chunk"/>
 <tile id="158" type="Chunk"/>
 <tile id="159" type="Chunk"/>
 <tile id="160" type="Chunk"/>
 <tile id="161" type="Chunk"/>
 <tile id="162" type="Chunk"/>
 <tile id="163" type="Chunk"/>
 <tile id="164" type="Chunk"/>
 <tile id="165" type="Chunk"/>
 <tile id="166" type="Chunk"/>
 <tile id="167" type="Chunk"/>
 <tile id="168" type="Chunk"/>
 <tile id="169" type="Chunk"/>
 <tile id="170" type="Chunk"/>
 <tile id="171" type="Chunk"/>
 <tile id="172" type="Chunk"/>
 <tile id="173" type="Chunk"/>
 <tile id="174" type="Chunk"/>
 <tile id="175" type="Chunk"/>
 <tile id="176" type="Chunk"/>
 <tile id="177" type="Chunk"/>
 <tile id="178" type="Chunk"/>
 <tile id="179" type="Chunk"/>
 <tile id="180" type="Chunk"/>
 <tile id="181" type="Chunk"/>
 <tile id="182" type="Chunk"/>
 <tile id="183" type="Chunk"/>
 <tile id="184" type="Chunk"/>
 <tile id="185" type="Chunk"/>
 <tile id="186" type="Chunk"/>
 <tile id="187" type="Chunk"/>
 <tile id="188" type="Chunk"/>
 <tile id="189" type="Chunk"/>
 <tile id="190" type="Chunk"/>
 <tile id="191" type="Chunk"/>
 <tile id="192" type="Chunk"/>
 <tile id="193" type="Chunk"/>
 <tile id="194" type="Chunk"/>
 <tile id="195" type="Chunk"/>
 <tile id="196" type="Chunk"/>
 <tile id="197" type="Chunk"/>
 <tile id="198" type="Chunk"/>
 <tile id="199" type="Chunk"/>
</tileset>
