<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.4" tiledversion="1.4.1" name="graphicblocks" tilewidth="16" tileheight="16" tilecount="45" columns="9">
 <image source="assets/graphics.png" width="144" height="80"/>
 <tile id="0" type="graphicsblock"/>
 <tile id="1" type="graphicsblock"/>
 <tile id="2" type="graphicsblock"/>
 <tile id="3" type="graphicsblock"/>
 <tile id="4" type="graphicsblock"/>
 <tile id="5" type="graphicsblock"/>
 <tile id="6" type="graphicsblock"/>
 <tile id="7" type="graphicsblock"/>
 <tile id="8" type="graphicsblock"/>
 <tile id="9" type="graphicsblock"/>
 <tile id="10" type="graphicsblock"/>
 <tile id="11" type="graphicsblock"/>
 <tile id="12" type="graphicsblock"/>
 <tile id="13" type="graphicsblock"/>
 <tile id="14" type="graphicsblock"/>
 <tile id="15" type="graphicsblock"/>
 <tile id="16" type="graphicsblock"/>
 <tile id="17" type="graphicsblock"/>
 <tile id="18" type="graphicsblock"/>
 <tile id="19" type="graphicsblock"/>
 <tile id="20" type="graphicsblock"/>
 <tile id="21" type="graphicsblock"/>
 <tile id="22" type="graphicsblock"/>
 <tile id="23" type="graphicsblock"/>
 <tile id="24" type="graphicsblock"/>
 <tile id="25" type="graphicsblock"/>
 <tile id="26" type="graphicsblock"/>
 <tile id="27" type="graphicsblock"/>
 <tile id="28" type="graphicsblock"/>
 <tile id="29" type="graphicsblock"/>
 <tile id="30" type="graphicsblock"/>
 <tile id="31" type="graphicsblock"/>
 <tile id="32" type="graphicsblock"/>
 <tile id="33" type="graphicsblock"/>
 <tile id="34" type="graphicsblock"/>
 <tile id="35" type="graphicsblock"/>
 <tile id="36" type="graphicsblock"/>
 <tile id="37" type="graphicsblock"/>
 <tile id="38" type="graphicsblock"/>
 <tile id="39" type="graphicsblock"/>
 <tile id="40" type="graphicsblock"/>
 <tile id="41" type="graphicsblock"/>
 <tile id="42" type="graphicsblock"/>
 <tile id="43" type="graphicsblock"/>
 <tile id="44" type="graphicsblock"/>
</tileset>
