;------------------------------------------------------------------------------------------
; Engine configuration
;------------------------------------------------------------------------------------------

    If (~def(__ENGINE_CONFIG_INC))
__ENGINE_CONFIG_INC Equ 1

;-------------------------------------------------
; Experimental feature toggles
; ----------------
MAP_OVERLAY_ENABLE              = 1
MAP_OVERLAY_COLLISION_ENABLE    = 1

    EndIf
