<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.5" tiledversion="1.6.0" name="Chunks" tilewidth="128" tileheight="128" tilecount="384" columns="16">
 <properties>
  <property name="colorTransitionTable" type="file" value="assets/colortransition.yaml"/>
  <property name="waterColor" type="color" value="#ff3400ce"/>
 </properties>
 <image source="chunks.tmx" width="2048" height="3072"/>
 <tile id="0" type="Chunk"/>
 <tile id="1" type="Chunk"/>
 <tile id="2" type="Chunk"/>
 <tile id="3" type="Chunk"/>
 <tile id="4" type="Chunk"/>
 <tile id="5" type="Chunk"/>
 <tile id="6" type="Chunk"/>
 <tile id="7" type="Chunk"/>
 <tile id="8" type="Chunk"/>
 <tile id="9" type="Chunk"/>
 <tile id="10" type="Chunk"/>
 <tile id="11" type="Chunk"/>
 <tile id="12" type="Chunk"/>
 <tile id="13" type="Chunk"/>
 <tile id="14" type="Chunk"/>
 <tile id="15" type="Chunk"/>
 <tile id="16" type="Chunk"/>
 <tile id="17" type="Chunk"/>
 <tile id="18" type="Chunk"/>
 <tile id="19" type="Chunk"/>
 <tile id="20" type="Chunk"/>
 <tile id="21" type="Chunk"/>
 <tile id="22" type="Chunk"/>
 <tile id="23" type="Chunk"/>
 <tile id="24" type="Chunk"/>
 <tile id="25" type="Chunk"/>
 <tile id="26" type="Chunk"/>
 <tile id="27" type="Chunk"/>
 <tile id="28" type="Chunk"/>
 <tile id="29" type="Chunk"/>
 <tile id="30" type="Chunk"/>
 <tile id="31" type="Chunk"/>
 <tile id="32" type="Chunk"/>
 <tile id="33" type="Chunk"/>
 <tile id="34" type="Chunk"/>
 <tile id="35" type="Chunk"/>
 <tile id="36" type="Chunk"/>
 <tile id="37" type="Chunk"/>
 <tile id="38" type="Chunk"/>
 <tile id="39" type="Chunk"/>
 <tile id="40" type="Chunk"/>
 <tile id="41" type="Chunk"/>
 <tile id="42" type="Chunk"/>
 <tile id="43" type="Chunk"/>
 <tile id="44" type="Chunk"/>
 <tile id="45" type="Chunk"/>
 <tile id="46" type="Chunk"/>
 <tile id="47" type="Chunk"/>
 <tile id="48" type="Chunk"/>
 <tile id="49" type="Chunk"/>
 <tile id="50" type="Chunk"/>
 <tile id="51" type="Chunk"/>
 <tile id="52" type="Chunk"/>
 <tile id="53" type="Chunk"/>
 <tile id="54" type="Chunk"/>
 <tile id="55" type="Chunk"/>
 <tile id="56" type="Chunk"/>
 <tile id="57" type="Chunk"/>
 <tile id="58" type="Chunk"/>
 <tile id="59" type="Chunk"/>
 <tile id="60" type="Chunk"/>
 <tile id="61" type="Chunk"/>
 <tile id="62" type="Chunk"/>
 <tile id="63" type="Chunk"/>
 <tile id="64" type="Chunk"/>
 <tile id="65" type="Chunk"/>
 <tile id="66" type="Chunk"/>
 <tile id="67" type="Chunk"/>
 <tile id="68" type="Chunk"/>
 <tile id="69" type="Chunk"/>
 <tile id="70" type="Chunk"/>
 <tile id="71" type="Chunk"/>
 <tile id="72" type="Chunk"/>
 <tile id="73" type="Chunk"/>
 <tile id="74" type="Chunk"/>
 <tile id="75" type="Chunk"/>
 <tile id="76" type="Chunk"/>
 <tile id="77" type="Chunk"/>
 <tile id="78" type="Chunk"/>
 <tile id="79" type="Chunk"/>
 <tile id="80" type="Chunk"/>
 <tile id="81" type="Chunk"/>
 <tile id="82" type="Chunk"/>
 <tile id="83" type="Chunk"/>
 <tile id="84" type="Chunk"/>
 <tile id="85" type="Chunk"/>
 <tile id="86" type="Chunk"/>
 <tile id="87" type="Chunk"/>
 <tile id="88" type="Chunk"/>
 <tile id="89" type="Chunk"/>
 <tile id="90" type="Chunk"/>
 <tile id="91" type="Chunk"/>
 <tile id="92" type="Chunk"/>
 <tile id="93" type="Chunk"/>
 <tile id="94" type="Chunk"/>
 <tile id="95" type="Chunk"/>
 <tile id="96" type="Chunk"/>
 <tile id="97" type="Chunk"/>
 <tile id="98" type="Chunk"/>
 <tile id="99" type="Chunk"/>
 <tile id="100" type="Chunk"/>
 <tile id="101" type="Chunk"/>
 <tile id="102" type="Chunk"/>
 <tile id="103" type="Chunk"/>
 <tile id="104" type="Chunk"/>
 <tile id="105" type="Chunk"/>
 <tile id="106" type="Chunk"/>
 <tile id="107" type="Chunk"/>
 <tile id="108" type="Chunk"/>
 <tile id="109" type="Chunk"/>
 <tile id="110" type="Chunk"/>
 <tile id="111" type="Chunk"/>
 <tile id="112" type="Chunk"/>
 <tile id="113" type="Chunk"/>
 <tile id="114" type="Chunk"/>
 <tile id="115" type="Chunk"/>
 <tile id="116" type="Chunk"/>
 <tile id="117" type="Chunk"/>
 <tile id="118" type="Chunk"/>
 <tile id="119" type="Chunk"/>
 <tile id="120" type="Chunk"/>
 <tile id="121" type="Chunk"/>
 <tile id="122" type="Chunk"/>
 <tile id="123" type="Chunk"/>
 <tile id="124" type="Chunk"/>
 <tile id="125" type="Chunk"/>
 <tile id="126" type="Chunk"/>
 <tile id="127" type="Chunk"/>
 <tile id="128" type="Chunk"/>
 <tile id="129" type="Chunk"/>
 <tile id="130" type="Chunk"/>
 <tile id="131" type="Chunk"/>
 <tile id="132" type="Chunk"/>
 <tile id="133" type="Chunk"/>
 <tile id="134" type="Chunk"/>
 <tile id="135" type="Chunk"/>
 <tile id="136" type="Chunk"/>
 <tile id="137" type="Chunk"/>
 <tile id="138" type="Chunk"/>
 <tile id="139" type="Chunk"/>
 <tile id="140" type="Chunk"/>
 <tile id="141" type="Chunk"/>
 <tile id="142" type="Chunk"/>
 <tile id="143" type="Chunk"/>
 <tile id="144" type="Chunk"/>
 <tile id="145" type="Chunk"/>
 <tile id="146" type="Chunk"/>
 <tile id="147" type="Chunk"/>
 <tile id="148" type="Chunk"/>
 <tile id="149" type="Chunk"/>
 <tile id="150" type="Chunk"/>
 <tile id="151" type="Chunk"/>
 <tile id="152" type="Chunk"/>
 <tile id="153" type="Chunk"/>
 <tile id="154" type="Chunk"/>
 <tile id="155" type="Chunk"/>
 <tile id="156" type="Chunk"/>
 <tile id="157" type="Chunk"/>
 <tile id="158" type="Chunk"/>
 <tile id="159" type="Chunk"/>
 <tile id="160" type="Chunk"/>
 <tile id="161" type="Chunk"/>
 <tile id="162" type="Chunk"/>
 <tile id="163" type="Chunk"/>
 <tile id="164" type="Chunk"/>
 <tile id="165" type="Chunk"/>
 <tile id="166" type="Chunk"/>
 <tile id="167" type="Chunk"/>
 <tile id="168" type="Chunk"/>
 <tile id="169" type="Chunk"/>
 <tile id="170" type="Chunk"/>
 <tile id="171" type="Chunk"/>
 <tile id="172" type="Chunk"/>
 <tile id="173" type="Chunk"/>
 <tile id="174" type="Chunk"/>
 <tile id="175" type="Chunk"/>
 <tile id="176" type="Chunk"/>
 <tile id="177" type="Chunk"/>
 <tile id="178" type="Chunk"/>
 <tile id="179" type="Chunk"/>
 <tile id="180" type="Chunk"/>
 <tile id="181" type="Chunk"/>
 <tile id="182" type="Chunk"/>
 <tile id="183" type="Chunk"/>
 <tile id="184" type="Chunk"/>
 <tile id="185" type="Chunk"/>
 <tile id="186" type="Chunk"/>
 <tile id="187" type="Chunk"/>
 <tile id="188" type="Chunk"/>
 <tile id="189" type="Chunk"/>
 <tile id="190" type="Chunk"/>
 <tile id="191" type="Chunk"/>
 <tile id="192" type="Chunk"/>
 <tile id="193" type="Chunk"/>
 <tile id="194" type="Chunk"/>
 <tile id="195" type="Chunk"/>
 <tile id="196" type="Chunk"/>
 <tile id="197" type="Chunk"/>
 <tile id="198" type="Chunk"/>
 <tile id="199" type="Chunk"/>
 <tile id="200" type="Chunk"/>
 <tile id="201" type="Chunk"/>
 <tile id="202" type="Chunk"/>
 <tile id="203" type="Chunk"/>
 <tile id="204" type="Chunk"/>
 <tile id="205" type="Chunk"/>
 <tile id="206" type="Chunk"/>
 <tile id="207" type="Chunk"/>
 <tile id="208" type="Chunk"/>
 <tile id="209" type="Chunk"/>
 <tile id="210" type="Chunk"/>
 <tile id="211" type="Chunk"/>
 <tile id="212" type="Chunk"/>
 <tile id="213" type="Chunk"/>
 <tile id="214" type="Chunk"/>
 <tile id="215" type="Chunk"/>
 <tile id="216" type="Chunk"/>
 <tile id="217" type="Chunk"/>
 <tile id="218" type="Chunk"/>
 <tile id="219" type="Chunk"/>
 <tile id="220" type="Chunk"/>
 <tile id="221" type="Chunk"/>
 <tile id="222" type="Chunk"/>
 <tile id="223" type="Chunk"/>
 <tile id="224" type="Chunk"/>
 <tile id="225" type="Chunk"/>
 <tile id="226" type="Chunk"/>
 <tile id="227" type="Chunk"/>
 <tile id="228" type="Chunk"/>
 <tile id="229" type="Chunk"/>
 <tile id="230" type="Chunk"/>
 <tile id="231" type="Chunk"/>
 <tile id="232" type="Chunk"/>
 <tile id="233" type="Chunk"/>
 <tile id="234" type="Chunk"/>
 <tile id="235" type="Chunk"/>
 <tile id="236" type="Chunk"/>
 <tile id="237" type="Chunk"/>
 <tile id="238" type="Chunk"/>
 <tile id="239" type="Chunk"/>
 <tile id="240" type="Chunk"/>
 <tile id="241" type="Chunk"/>
 <tile id="242" type="Chunk"/>
 <tile id="243" type="Chunk"/>
 <tile id="244" type="Chunk"/>
 <tile id="245" type="Chunk"/>
 <tile id="246" type="Chunk"/>
 <tile id="247" type="Chunk"/>
 <tile id="248" type="Chunk"/>
 <tile id="249" type="Chunk"/>
 <tile id="250" type="Chunk"/>
 <tile id="251" type="Chunk"/>
 <tile id="252" type="Chunk"/>
 <tile id="253" type="Chunk"/>
 <tile id="254" type="Chunk"/>
 <tile id="255" type="Chunk"/>
 <tile id="256" type="Chunk"/>
 <tile id="257" type="Chunk"/>
 <tile id="258" type="Chunk"/>
 <tile id="259" type="Chunk"/>
 <tile id="260" type="Chunk"/>
 <tile id="261" type="Chunk"/>
 <tile id="262" type="Chunk"/>
 <tile id="263" type="Chunk"/>
 <tile id="264" type="Chunk"/>
 <tile id="265" type="Chunk"/>
 <tile id="266" type="Chunk"/>
 <tile id="267" type="Chunk"/>
 <tile id="268" type="Chunk"/>
 <tile id="269" type="Chunk"/>
 <tile id="270" type="Chunk"/>
 <tile id="271" type="Chunk"/>
 <tile id="272" type="Chunk"/>
 <tile id="273" type="Chunk"/>
 <tile id="274" type="Chunk"/>
 <tile id="275" type="Chunk"/>
 <tile id="276" type="Chunk"/>
 <tile id="277" type="Chunk"/>
 <tile id="278" type="Chunk"/>
 <tile id="279" type="Chunk"/>
 <tile id="280" type="Chunk"/>
 <tile id="281" type="Chunk"/>
 <tile id="282" type="Chunk"/>
 <tile id="283" type="Chunk"/>
 <tile id="284" type="Chunk"/>
 <tile id="285" type="Chunk"/>
 <tile id="286" type="Chunk"/>
 <tile id="287" type="Chunk"/>
 <tile id="288" type="Chunk"/>
 <tile id="289" type="Chunk"/>
 <tile id="290" type="Chunk"/>
 <tile id="291" type="Chunk"/>
 <tile id="292" type="Chunk"/>
 <tile id="293" type="Chunk"/>
 <tile id="294" type="Chunk"/>
 <tile id="295" type="Chunk"/>
 <tile id="296" type="Chunk"/>
 <tile id="297" type="Chunk"/>
 <tile id="298" type="Chunk"/>
 <tile id="299" type="Chunk"/>
 <tile id="300" type="Chunk"/>
 <tile id="301" type="Chunk"/>
 <tile id="302" type="Chunk"/>
 <tile id="303" type="Chunk"/>
 <tile id="304" type="Chunk"/>
 <tile id="305" type="Chunk"/>
 <tile id="306" type="Chunk"/>
 <tile id="307" type="Chunk"/>
 <tile id="308" type="Chunk"/>
 <tile id="309" type="Chunk"/>
 <tile id="310" type="Chunk"/>
 <tile id="311" type="Chunk"/>
 <tile id="312" type="Chunk"/>
 <tile id="313" type="Chunk"/>
 <tile id="314" type="Chunk"/>
 <tile id="315" type="Chunk"/>
 <tile id="316" type="Chunk"/>
 <tile id="317" type="Chunk"/>
 <tile id="318" type="Chunk"/>
 <tile id="319" type="Chunk"/>
 <tile id="320" type="Chunk"/>
 <tile id="321" type="Chunk"/>
 <tile id="322" type="Chunk"/>
 <tile id="323" type="Chunk"/>
 <tile id="324" type="Chunk"/>
 <tile id="325" type="Chunk"/>
 <tile id="326" type="Chunk"/>
 <tile id="327" type="Chunk"/>
 <tile id="328" type="Chunk"/>
 <tile id="329" type="Chunk"/>
 <tile id="330" type="Chunk"/>
 <tile id="331" type="Chunk"/>
 <tile id="332" type="Chunk"/>
 <tile id="333" type="Chunk"/>
 <tile id="334" type="Chunk"/>
 <tile id="335" type="Chunk"/>
 <tile id="336" type="Chunk"/>
 <tile id="337" type="Chunk"/>
 <tile id="338" type="Chunk"/>
 <tile id="339" type="Chunk"/>
 <tile id="340" type="Chunk"/>
 <tile id="341" type="Chunk"/>
 <tile id="342" type="Chunk"/>
 <tile id="343" type="Chunk"/>
 <tile id="344" type="Chunk"/>
 <tile id="345" type="Chunk"/>
 <tile id="346" type="Chunk"/>
 <tile id="347" type="Chunk"/>
 <tile id="348" type="Chunk"/>
 <tile id="349" type="Chunk"/>
 <tile id="350" type="Chunk"/>
 <tile id="351" type="Chunk"/>
 <tile id="352" type="Chunk"/>
 <tile id="353" type="Chunk"/>
 <tile id="354" type="Chunk"/>
 <tile id="355" type="Chunk"/>
 <tile id="356" type="Chunk"/>
 <tile id="357" type="Chunk"/>
 <tile id="358" type="Chunk"/>
 <tile id="359" type="Chunk"/>
 <tile id="360" type="Chunk"/>
 <tile id="361" type="Chunk"/>
 <tile id="362" type="Chunk"/>
 <tile id="363" type="Chunk"/>
 <tile id="364" type="Chunk"/>
 <tile id="365" type="Chunk"/>
 <tile id="366" type="Chunk"/>
 <tile id="367" type="Chunk"/>
 <tile id="368" type="Chunk"/>
 <tile id="369" type="Chunk"/>
 <tile id="370" type="Chunk"/>
 <tile id="371" type="Chunk"/>
 <tile id="372" type="Chunk"/>
 <tile id="373" type="Chunk"/>
 <tile id="374" type="Chunk"/>
 <tile id="375" type="Chunk"/>
 <tile id="376" type="Chunk"/>
 <tile id="377" type="Chunk"/>
 <tile id="378" type="Chunk"/>
 <tile id="379" type="Chunk"/>
 <tile id="380" type="Chunk"/>
 <tile id="381" type="Chunk"/>
 <tile id="382" type="Chunk"/>
 <tile id="383" type="Chunk"/>
</tileset>
