<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.4" tiledversion="1.4.2" name="Blocks" tilewidth="16" tileheight="16" tilecount="984" columns="24">
 <image source="blocks.tmx" width="384" height="656"/>
 <tile id="0" type="Block"/>
 <tile id="1" type="Block"/>
 <tile id="2" type="Block"/>
 <tile id="3" type="Block"/>
 <tile id="4" type="Block"/>
 <tile id="5" type="Block"/>
 <tile id="6" type="Block"/>
 <tile id="7" type="Block"/>
 <tile id="8" type="Block"/>
 <tile id="9" type="Block"/>
 <tile id="10" type="Block"/>
 <tile id="11" type="Block"/>
 <tile id="12" type="Block"/>
 <tile id="13" type="Block"/>
 <tile id="14" type="Block"/>
 <tile id="15" type="Block"/>
 <tile id="16" type="Block"/>
 <tile id="17" type="Block"/>
 <tile id="18" type="Block"/>
 <tile id="19" type="Block"/>
 <tile id="20" type="Block"/>
 <tile id="21" type="Block"/>
 <tile id="22" type="Block"/>
 <tile id="23" type="Block"/>
 <tile id="24" type="Block"/>
 <tile id="25" type="Block"/>
 <tile id="26" type="Block"/>
 <tile id="27" type="Block"/>
 <tile id="28" type="Block"/>
 <tile id="29" type="Block"/>
 <tile id="30" type="Block"/>
 <tile id="31" type="Block"/>
 <tile id="32" type="Block"/>
 <tile id="33" type="Block"/>
 <tile id="34" type="Block"/>
 <tile id="35" type="Block"/>
 <tile id="36" type="Block"/>
 <tile id="37" type="Block"/>
 <tile id="38" type="Block"/>
 <tile id="39" type="Block"/>
 <tile id="40" type="Block"/>
 <tile id="41" type="Block"/>
 <tile id="42" type="Block"/>
 <tile id="43" type="Block"/>
 <tile id="44" type="Block"/>
 <tile id="45" type="Block"/>
 <tile id="46" type="Block"/>
 <tile id="47" type="Block"/>
 <tile id="48" type="Block"/>
 <tile id="49" type="Block"/>
 <tile id="50" type="Block"/>
 <tile id="51" type="Block"/>
 <tile id="52" type="Block"/>
 <tile id="53" type="Block"/>
 <tile id="54" type="Block"/>
 <tile id="55" type="Block"/>
 <tile id="56" type="Block"/>
 <tile id="57" type="Block"/>
 <tile id="58" type="Block"/>
 <tile id="59" type="Block"/>
 <tile id="60" type="Block"/>
 <tile id="61" type="Block"/>
 <tile id="62" type="Block"/>
 <tile id="63" type="Block"/>
 <tile id="64" type="Block"/>
 <tile id="65" type="Block"/>
 <tile id="66" type="Block"/>
 <tile id="67" type="Block"/>
 <tile id="68" type="Block"/>
 <tile id="69" type="Block"/>
 <tile id="70" type="Block"/>
 <tile id="71" type="Block"/>
 <tile id="72" type="Block"/>
 <tile id="73" type="Block"/>
 <tile id="74" type="Block"/>
 <tile id="75" type="Block"/>
 <tile id="76" type="Block"/>
 <tile id="77" type="Block"/>
 <tile id="78" type="Block"/>
 <tile id="79" type="Block"/>
 <tile id="80" type="Block"/>
 <tile id="81" type="Block"/>
 <tile id="82" type="Block"/>
 <tile id="83" type="Block"/>
 <tile id="84" type="Block"/>
 <tile id="85" type="Block"/>
 <tile id="86" type="Block"/>
 <tile id="87" type="Block"/>
 <tile id="88" type="Block"/>
 <tile id="89" type="Block"/>
 <tile id="90" type="Block"/>
 <tile id="91" type="Block"/>
 <tile id="92" type="Block"/>
 <tile id="93" type="Block"/>
 <tile id="94" type="Block"/>
 <tile id="95" type="Block"/>
 <tile id="96" type="Block"/>
 <tile id="97" type="Block"/>
 <tile id="98" type="Block"/>
 <tile id="99" type="Block"/>
 <tile id="100" type="Block"/>
 <tile id="101" type="Block"/>
 <tile id="102" type="Block"/>
 <tile id="103" type="Block"/>
 <tile id="104" type="Block"/>
 <tile id="105" type="Block"/>
 <tile id="106" type="Block"/>
 <tile id="107" type="Block"/>
 <tile id="108" type="Block"/>
 <tile id="109" type="Block"/>
 <tile id="110" type="Block"/>
 <tile id="111" type="Block"/>
 <tile id="112" type="Block"/>
 <tile id="113" type="Block"/>
 <tile id="114" type="Block"/>
 <tile id="115" type="Block"/>
 <tile id="116" type="Block"/>
 <tile id="117" type="Block"/>
 <tile id="118" type="Block"/>
 <tile id="119" type="Block"/>
 <tile id="120" type="Block"/>
 <tile id="121" type="Block"/>
 <tile id="122" type="Block"/>
 <tile id="123" type="Block"/>
 <tile id="124" type="Block"/>
 <tile id="125" type="Block"/>
 <tile id="126" type="Block"/>
 <tile id="127" type="Block"/>
 <tile id="128" type="Block"/>
 <tile id="129" type="Block"/>
 <tile id="130" type="Block"/>
 <tile id="131" type="Block"/>
 <tile id="132" type="Block"/>
 <tile id="133" type="Block"/>
 <tile id="134" type="Block"/>
 <tile id="135" type="Block"/>
 <tile id="136" type="Block"/>
 <tile id="137" type="Block"/>
 <tile id="138" type="Block"/>
 <tile id="139" type="Block"/>
 <tile id="140" type="Block"/>
 <tile id="141" type="Block"/>
 <tile id="142" type="Block"/>
 <tile id="143" type="Block"/>
 <tile id="144" type="Block"/>
 <tile id="145" type="Block"/>
 <tile id="146" type="Block"/>
 <tile id="147" type="Block"/>
 <tile id="148" type="Block"/>
 <tile id="149" type="Block"/>
 <tile id="150" type="Block"/>
 <tile id="151" type="Block"/>
 <tile id="152" type="Block"/>
 <tile id="153" type="Block"/>
 <tile id="154" type="Block"/>
 <tile id="155" type="Block"/>
 <tile id="156" type="Block"/>
 <tile id="157" type="Block"/>
 <tile id="158" type="Block"/>
 <tile id="159" type="Block"/>
 <tile id="160" type="Block"/>
 <tile id="161" type="Block"/>
 <tile id="162" type="Block"/>
 <tile id="163" type="Block"/>
 <tile id="164" type="Block"/>
 <tile id="165" type="Block"/>
 <tile id="166" type="Block"/>
 <tile id="167" type="Block"/>
 <tile id="168" type="Block"/>
 <tile id="169" type="Block"/>
 <tile id="170" type="Block"/>
 <tile id="171" type="Block"/>
 <tile id="172" type="Block"/>
 <tile id="173" type="Block"/>
 <tile id="174" type="Block"/>
 <tile id="175" type="Block"/>
 <tile id="176" type="Block"/>
 <tile id="177" type="Block"/>
 <tile id="178" type="Block"/>
 <tile id="179" type="Block"/>
 <tile id="180" type="Block"/>
 <tile id="181" type="Block"/>
 <tile id="182" type="Block"/>
 <tile id="183" type="Block"/>
 <tile id="184" type="Block"/>
 <tile id="185" type="Block"/>
 <tile id="186" type="Block"/>
 <tile id="187" type="Block"/>
 <tile id="188" type="Block"/>
 <tile id="189" type="Block"/>
 <tile id="190" type="Block"/>
 <tile id="191" type="Block"/>
 <tile id="192" type="Block"/>
 <tile id="193" type="Block"/>
 <tile id="194" type="Block"/>
 <tile id="195" type="Block"/>
 <tile id="196" type="Block"/>
 <tile id="197" type="Block"/>
 <tile id="198" type="Block"/>
 <tile id="199" type="Block"/>
 <tile id="200" type="Block"/>
 <tile id="201" type="Block"/>
 <tile id="202" type="Block"/>
 <tile id="203" type="Block"/>
 <tile id="204" type="Block"/>
 <tile id="205" type="Block"/>
 <tile id="206" type="Block"/>
 <tile id="207" type="Block"/>
 <tile id="208" type="Block"/>
 <tile id="209" type="Block"/>
 <tile id="210" type="Block"/>
 <tile id="211" type="Block"/>
 <tile id="212" type="Block"/>
 <tile id="213" type="Block"/>
 <tile id="214" type="Block"/>
 <tile id="215" type="Block"/>
 <tile id="216" type="Block"/>
 <tile id="217" type="Block"/>
 <tile id="218" type="Block"/>
 <tile id="219" type="Block"/>
 <tile id="220" type="Block"/>
 <tile id="221" type="Block"/>
 <tile id="222" type="Block"/>
 <tile id="223" type="Block"/>
 <tile id="224" type="Block"/>
 <tile id="225" type="Block"/>
 <tile id="226" type="Block"/>
 <tile id="227" type="Block"/>
 <tile id="228" type="Block"/>
 <tile id="229" type="Block"/>
 <tile id="230" type="Block"/>
 <tile id="231" type="Block"/>
 <tile id="232" type="Block"/>
 <tile id="233" type="Block"/>
 <tile id="234" type="Block"/>
 <tile id="235" type="Block"/>
 <tile id="236" type="Block"/>
 <tile id="237" type="Block"/>
 <tile id="238" type="Block"/>
 <tile id="239" type="Block"/>
 <tile id="240" type="Block"/>
 <tile id="241" type="Block"/>
 <tile id="242" type="Block"/>
 <tile id="243" type="Block"/>
 <tile id="244" type="Block"/>
 <tile id="245" type="Block"/>
 <tile id="246" type="Block"/>
 <tile id="247" type="Block"/>
 <tile id="248" type="Block"/>
 <tile id="249" type="Block"/>
 <tile id="250" type="Block"/>
 <tile id="251" type="Block"/>
 <tile id="252" type="Block"/>
 <tile id="253" type="Block"/>
 <tile id="254" type="Block"/>
 <tile id="255" type="Block"/>
 <tile id="256" type="Block"/>
 <tile id="257" type="Block"/>
 <tile id="258" type="Block"/>
 <tile id="259" type="Block"/>
 <tile id="260" type="Block"/>
 <tile id="261" type="Block"/>
 <tile id="262" type="Block"/>
 <tile id="263" type="Block"/>
 <tile id="264" type="Block"/>
 <tile id="265" type="Block"/>
 <tile id="266" type="Block"/>
 <tile id="267" type="Block"/>
 <tile id="268" type="Block"/>
 <tile id="269" type="Block"/>
 <tile id="270" type="Block"/>
 <tile id="271" type="Block"/>
 <tile id="272" type="Block"/>
 <tile id="273" type="Block"/>
 <tile id="274" type="Block"/>
 <tile id="275" type="Block"/>
 <tile id="276" type="Block"/>
 <tile id="277" type="Block"/>
 <tile id="278" type="Block"/>
 <tile id="279" type="Block"/>
 <tile id="280" type="Block"/>
 <tile id="281" type="Block"/>
 <tile id="282" type="Block"/>
 <tile id="283" type="Block"/>
 <tile id="284" type="Block"/>
 <tile id="285" type="Block"/>
 <tile id="286" type="Block"/>
 <tile id="287" type="Block"/>
 <tile id="288" type="Block"/>
 <tile id="289" type="Block"/>
 <tile id="290" type="Block"/>
 <tile id="291" type="Block"/>
 <tile id="292" type="Block"/>
 <tile id="293" type="Block"/>
 <tile id="294" type="Block"/>
 <tile id="295" type="Block"/>
 <tile id="296" type="Block"/>
 <tile id="297" type="Block"/>
 <tile id="298" type="Block"/>
 <tile id="299" type="Block"/>
 <tile id="300" type="Block"/>
 <tile id="301" type="Block"/>
 <tile id="302" type="Block"/>
 <tile id="303" type="Block"/>
 <tile id="304" type="Block"/>
 <tile id="305" type="Block"/>
 <tile id="306" type="Block"/>
 <tile id="307" type="Block"/>
 <tile id="308" type="Block"/>
 <tile id="309" type="Block"/>
 <tile id="310" type="Block"/>
 <tile id="311" type="Block"/>
 <tile id="312" type="Block"/>
 <tile id="313" type="Block"/>
 <tile id="314" type="Block"/>
 <tile id="315" type="Block"/>
 <tile id="316" type="Block"/>
 <tile id="317" type="Block"/>
 <tile id="318" type="Block"/>
 <tile id="319" type="Block"/>
 <tile id="320" type="Block"/>
 <tile id="321" type="Block"/>
 <tile id="322" type="Block"/>
 <tile id="323" type="Block"/>
 <tile id="324" type="Block"/>
 <tile id="325" type="Block"/>
 <tile id="326" type="Block"/>
 <tile id="327" type="Block"/>
 <tile id="328" type="Block"/>
 <tile id="329" type="Block"/>
 <tile id="330" type="Block"/>
 <tile id="331" type="Block"/>
 <tile id="332" type="Block"/>
 <tile id="333" type="Block"/>
 <tile id="334" type="Block"/>
 <tile id="335" type="Block"/>
 <tile id="336" type="Block"/>
 <tile id="337" type="Block"/>
 <tile id="338" type="Block"/>
 <tile id="339" type="Block"/>
 <tile id="340" type="Block"/>
 <tile id="341" type="Block"/>
 <tile id="342" type="Block"/>
 <tile id="343" type="Block"/>
 <tile id="344" type="Block"/>
 <tile id="345" type="Block"/>
 <tile id="346" type="Block"/>
 <tile id="347" type="Block"/>
 <tile id="348" type="Block"/>
 <tile id="349" type="Block"/>
 <tile id="350" type="Block"/>
 <tile id="351" type="Block"/>
 <tile id="352" type="Block"/>
 <tile id="353" type="Block"/>
 <tile id="354" type="Block"/>
 <tile id="355" type="Block"/>
 <tile id="356" type="Block"/>
 <tile id="357" type="Block"/>
 <tile id="358" type="Block"/>
 <tile id="359" type="Block"/>
 <tile id="360" type="Block"/>
 <tile id="361" type="Block"/>
 <tile id="362" type="Block"/>
 <tile id="363" type="Block"/>
 <tile id="364" type="Block"/>
 <tile id="365" type="Block"/>
 <tile id="366" type="Block"/>
 <tile id="367" type="Block"/>
 <tile id="368" type="Block"/>
 <tile id="369" type="Block"/>
 <tile id="370" type="Block"/>
 <tile id="371" type="Block"/>
 <tile id="372" type="Block"/>
 <tile id="373" type="Block"/>
 <tile id="374" type="Block"/>
 <tile id="375" type="Block"/>
 <tile id="376" type="Block"/>
 <tile id="377" type="Block"/>
 <tile id="378" type="Block"/>
 <tile id="379" type="Block"/>
 <tile id="380" type="Block"/>
 <tile id="381" type="Block"/>
 <tile id="382" type="Block"/>
 <tile id="383" type="Block"/>
 <tile id="384" type="Block"/>
 <tile id="385" type="Block"/>
 <tile id="386" type="Block"/>
 <tile id="387" type="Block"/>
 <tile id="388" type="Block"/>
 <tile id="389" type="Block"/>
 <tile id="390" type="Block"/>
 <tile id="391" type="Block"/>
 <tile id="392" type="Block"/>
 <tile id="393" type="Block"/>
 <tile id="394" type="Block"/>
 <tile id="395" type="Block"/>
 <tile id="396" type="Block"/>
 <tile id="397" type="Block"/>
 <tile id="398" type="Block"/>
 <tile id="399" type="Block"/>
 <tile id="400" type="Block"/>
 <tile id="401" type="Block"/>
 <tile id="402" type="Block"/>
 <tile id="403" type="Block"/>
 <tile id="404" type="Block"/>
 <tile id="405" type="Block"/>
 <tile id="406" type="Block"/>
 <tile id="407" type="Block"/>
 <tile id="408" type="Block"/>
 <tile id="409" type="Block"/>
 <tile id="410" type="Block"/>
 <tile id="411" type="Block"/>
 <tile id="412" type="Block"/>
 <tile id="413" type="Block"/>
 <tile id="414" type="Block"/>
 <tile id="415" type="Block"/>
 <tile id="416" type="Block"/>
 <tile id="417" type="Block"/>
 <tile id="418" type="Block"/>
 <tile id="419" type="Block"/>
 <tile id="420" type="Block"/>
 <tile id="421" type="Block"/>
 <tile id="422" type="Block"/>
 <tile id="423" type="Block"/>
 <tile id="424" type="Block"/>
 <tile id="425" type="Block"/>
 <tile id="426" type="Block"/>
 <tile id="427" type="Block"/>
 <tile id="428" type="Block"/>
 <tile id="429" type="Block"/>
 <tile id="430" type="Block"/>
 <tile id="431" type="Block"/>
 <tile id="432" type="AnimationBlock">
  <properties>
   <property name="animation_id" value="lava"/>
   <property name="animation_initial_trigger" type="int" value="1"/>
   <property name="animation_trigger_interval" type="int" value="1"/>
  </properties>
  <animation>
   <frame tileid="432" duration="100"/>
   <frame tileid="434" duration="100"/>
   <frame tileid="436" duration="100"/>
   <frame tileid="438" duration="100"/>
   <frame tileid="440" duration="100"/>
   <frame tileid="442" duration="100"/>
   <frame tileid="444" duration="100"/>
   <frame tileid="446" duration="100"/>
   <frame tileid="448" duration="100"/>
   <frame tileid="450" duration="100"/>
   <frame tileid="452" duration="100"/>
   <frame tileid="454" duration="100"/>
   <frame tileid="456" duration="100"/>
   <frame tileid="458" duration="100"/>
   <frame tileid="460" duration="100"/>
   <frame tileid="462" duration="100"/>
  </animation>
 </tile>
 <tile id="433" type="AnimationBlock">
  <properties>
   <property name="animation_id" value="lava"/>
  </properties>
  <animation>
   <frame tileid="433" duration="100"/>
   <frame tileid="435" duration="100"/>
   <frame tileid="437" duration="100"/>
   <frame tileid="439" duration="100"/>
   <frame tileid="441" duration="100"/>
   <frame tileid="443" duration="100"/>
   <frame tileid="445" duration="100"/>
   <frame tileid="447" duration="100"/>
   <frame tileid="449" duration="100"/>
   <frame tileid="451" duration="100"/>
   <frame tileid="453" duration="100"/>
   <frame tileid="455" duration="100"/>
   <frame tileid="457" duration="100"/>
   <frame tileid="459" duration="100"/>
   <frame tileid="461" duration="100"/>
   <frame tileid="463" duration="100"/>
  </animation>
 </tile>
 <tile id="434" type="Block"/>
 <tile id="435" type="Block"/>
 <tile id="436" type="Block"/>
 <tile id="437" type="Block"/>
 <tile id="438" type="Block"/>
 <tile id="439" type="Block"/>
 <tile id="440" type="Block"/>
 <tile id="441" type="Block"/>
 <tile id="442" type="Block"/>
 <tile id="443" type="Block"/>
 <tile id="444" type="Block"/>
 <tile id="445" type="Block"/>
 <tile id="446" type="Block"/>
 <tile id="447" type="Block"/>
 <tile id="448" type="Block"/>
 <tile id="449" type="Block"/>
 <tile id="450" type="Block"/>
 <tile id="451" type="Block"/>
 <tile id="452" type="Block"/>
 <tile id="453" type="Block"/>
 <tile id="454" type="Block"/>
 <tile id="455" type="Block"/>
 <tile id="456" type="Block"/>
 <tile id="457" type="Block"/>
 <tile id="458" type="Block"/>
 <tile id="459" type="Block"/>
 <tile id="460" type="Block"/>
 <tile id="461" type="Block"/>
 <tile id="462" type="Block"/>
 <tile id="463" type="Block"/>
 <tile id="464" type="Block"/>
 <tile id="465" type="Block"/>
 <tile id="466" type="Block"/>
 <tile id="467" type="Block"/>
 <tile id="468" type="Block"/>
 <tile id="469" type="Block"/>
 <tile id="470" type="Block"/>
 <tile id="471" type="Block"/>
 <tile id="472" type="Block"/>
 <tile id="473" type="Block"/>
 <tile id="474" type="Block"/>
 <tile id="475" type="Block"/>
 <tile id="476" type="Block"/>
 <tile id="477" type="Block"/>
 <tile id="478" type="Block"/>
 <tile id="479" type="Block"/>
 <tile id="480" type="AnimationBlock">
  <properties>
   <property name="animation_frame_interval" type="int" value="2"/>
   <property name="animation_id" value="lava_slow"/>
   <property name="animation_initial_trigger" type="int" value="7"/>
   <property name="animation_trigger_interval" type="int" value="1"/>
  </properties>
  <animation>
   <frame tileid="480" duration="100"/>
   <frame tileid="482" duration="100"/>
   <frame tileid="484" duration="100"/>
   <frame tileid="486" duration="100"/>
   <frame tileid="488" duration="100"/>
   <frame tileid="490" duration="100"/>
   <frame tileid="492" duration="100"/>
   <frame tileid="494" duration="100"/>
   <frame tileid="496" duration="100"/>
   <frame tileid="498" duration="100"/>
   <frame tileid="500" duration="100"/>
   <frame tileid="502" duration="100"/>
   <frame tileid="504" duration="100"/>
   <frame tileid="506" duration="100"/>
   <frame tileid="508" duration="100"/>
   <frame tileid="510" duration="100"/>
  </animation>
 </tile>
 <tile id="481" type="AnimationBlock">
  <properties>
   <property name="animation_id" value="lava_slow"/>
  </properties>
  <animation>
   <frame tileid="481" duration="100"/>
   <frame tileid="483" duration="100"/>
   <frame tileid="485" duration="100"/>
   <frame tileid="487" duration="100"/>
   <frame tileid="489" duration="100"/>
   <frame tileid="491" duration="100"/>
   <frame tileid="493" duration="100"/>
   <frame tileid="495" duration="100"/>
   <frame tileid="497" duration="100"/>
   <frame tileid="499" duration="100"/>
   <frame tileid="501" duration="100"/>
   <frame tileid="503" duration="100"/>
   <frame tileid="505" duration="100"/>
   <frame tileid="507" duration="100"/>
   <frame tileid="509" duration="100"/>
   <frame tileid="511" duration="100"/>
  </animation>
 </tile>
 <tile id="482" type="Block"/>
 <tile id="483" type="Block"/>
 <tile id="484" type="Block"/>
 <tile id="485" type="Block"/>
 <tile id="486" type="Block"/>
 <tile id="487" type="Block"/>
 <tile id="488" type="Block"/>
 <tile id="489" type="Block"/>
 <tile id="490" type="Block"/>
 <tile id="491" type="Block"/>
 <tile id="492" type="Block"/>
 <tile id="493" type="Block"/>
 <tile id="494" type="Block"/>
 <tile id="495" type="Block"/>
 <tile id="496" type="Block"/>
 <tile id="497" type="Block"/>
 <tile id="498" type="Block"/>
 <tile id="499" type="Block"/>
 <tile id="500" type="Block"/>
 <tile id="501" type="Block"/>
 <tile id="502" type="Block"/>
 <tile id="503" type="Block"/>
 <tile id="504" type="Block"/>
 <tile id="505" type="Block"/>
 <tile id="506" type="Block"/>
 <tile id="507" type="Block"/>
 <tile id="508" type="Block"/>
 <tile id="509" type="Block"/>
 <tile id="510" type="Block"/>
 <tile id="511" type="Block"/>
 <tile id="512" type="Block"/>
 <tile id="513" type="Block"/>
 <tile id="514" type="Block"/>
 <tile id="515" type="Block"/>
 <tile id="516" type="Block"/>
 <tile id="517" type="Block"/>
 <tile id="518" type="Block"/>
 <tile id="519" type="Block"/>
 <tile id="520" type="Block"/>
 <tile id="521" type="Block"/>
 <tile id="522" type="Block"/>
 <tile id="523" type="Block"/>
 <tile id="524" type="Block"/>
 <tile id="525" type="Block"/>
 <tile id="526" type="Block"/>
 <tile id="527" type="Block"/>
 <tile id="528" type="AnimationBlock">
  <properties>
   <property name="animation_frame_interval" type="int" value="6"/>
   <property name="animation_id" value="newton_cradle_start"/>
   <property name="animation_initial_trigger" type="int" value="1"/>
   <property name="animation_trigger_interval" type="int" value="54"/>
  </properties>
  <animation>
   <frame tileid="528" duration="100"/>
   <frame tileid="530" duration="100"/>
   <frame tileid="532" duration="100"/>
   <frame tileid="534" duration="100"/>
   <frame tileid="536" duration="100"/>
   <frame tileid="534" duration="100"/>
   <frame tileid="532" duration="100"/>
   <frame tileid="530" duration="100"/>
   <frame tileid="528" duration="100"/>
  </animation>
 </tile>
 <tile id="529" type="AnimationBlock">
  <properties>
   <property name="animation_id" value="newton_cradle_start"/>
  </properties>
  <animation>
   <frame tileid="529" duration="100"/>
   <frame tileid="531" duration="100"/>
   <frame tileid="533" duration="100"/>
   <frame tileid="535" duration="100"/>
   <frame tileid="537" duration="100"/>
   <frame tileid="535" duration="100"/>
   <frame tileid="533" duration="100"/>
   <frame tileid="531" duration="100"/>
   <frame tileid="529" duration="100"/>
  </animation>
 </tile>
 <tile id="530" type="Block"/>
 <tile id="531" type="Block"/>
 <tile id="532" type="Block"/>
 <tile id="533" type="Block"/>
 <tile id="534" type="Block"/>
 <tile id="535" type="Block"/>
 <tile id="536" type="Block"/>
 <tile id="537" type="Block"/>
 <tile id="538" type="Block"/>
 <tile id="539" type="Block"/>
 <tile id="540" type="Block"/>
 <tile id="541" type="Block"/>
 <tile id="542" type="Block"/>
 <tile id="543" type="Block"/>
 <tile id="544" type="Block"/>
 <tile id="545" type="Block"/>
 <tile id="546" type="Block"/>
 <tile id="547" type="Block"/>
 <tile id="548" type="Block"/>
 <tile id="549" type="Block"/>
 <tile id="550" type="Block"/>
 <tile id="551" type="Block"/>
 <tile id="552" type="AnimationBlock">
  <properties>
   <property name="animation_id" value="newton_cradle_start"/>
  </properties>
  <animation>
   <frame tileid="552" duration="100"/>
   <frame tileid="554" duration="100"/>
   <frame tileid="556" duration="100"/>
   <frame tileid="558" duration="100"/>
   <frame tileid="560" duration="100"/>
   <frame tileid="558" duration="100"/>
   <frame tileid="556" duration="100"/>
   <frame tileid="554" duration="100"/>
   <frame tileid="552" duration="100"/>
  </animation>
 </tile>
 <tile id="553" type="AnimationBlock">
  <properties>
   <property name="animation_id" value="newton_cradle_start"/>
  </properties>
  <animation>
   <frame tileid="553" duration="100"/>
   <frame tileid="555" duration="100"/>
   <frame tileid="557" duration="100"/>
   <frame tileid="559" duration="100"/>
   <frame tileid="561" duration="100"/>
   <frame tileid="559" duration="100"/>
   <frame tileid="557" duration="100"/>
   <frame tileid="555" duration="100"/>
   <frame tileid="553" duration="100"/>
  </animation>
 </tile>
 <tile id="554" type="Block"/>
 <tile id="555" type="Block"/>
 <tile id="556" type="Block"/>
 <tile id="557" type="Block"/>
 <tile id="558" type="Block"/>
 <tile id="559" type="Block"/>
 <tile id="560" type="Block"/>
 <tile id="561" type="Block"/>
 <tile id="562" type="Block"/>
 <tile id="563" type="Block"/>
 <tile id="564" type="Block"/>
 <tile id="565" type="Block"/>
 <tile id="566" type="Block"/>
 <tile id="567" type="Block"/>
 <tile id="568" type="Block"/>
 <tile id="569" type="Block"/>
 <tile id="570" type="Block"/>
 <tile id="571" type="Block"/>
 <tile id="572" type="Block"/>
 <tile id="573" type="Block"/>
 <tile id="574" type="Block"/>
 <tile id="575" type="Block"/>
 <tile id="576" type="AnimationBlock">
  <properties>
   <property name="animation_frame_interval" type="int" value="6"/>
   <property name="animation_id" value="newton_cradle_end"/>
   <property name="animation_initial_trigger" type="int" value="54"/>
   <property name="animation_trigger_interval" type="int" value="54"/>
  </properties>
  <animation>
   <frame tileid="576" duration="100"/>
   <frame tileid="578" duration="100"/>
   <frame tileid="580" duration="100"/>
   <frame tileid="582" duration="100"/>
   <frame tileid="584" duration="100"/>
   <frame tileid="582" duration="100"/>
   <frame tileid="580" duration="100"/>
   <frame tileid="578" duration="100"/>
   <frame tileid="576" duration="100"/>
  </animation>
 </tile>
 <tile id="577" type="AnimationBlock">
  <properties>
   <property name="animation_id" value="newton_cradle_end"/>
  </properties>
  <animation>
   <frame tileid="577" duration="100"/>
   <frame tileid="579" duration="100"/>
   <frame tileid="581" duration="100"/>
   <frame tileid="583" duration="100"/>
   <frame tileid="585" duration="100"/>
   <frame tileid="583" duration="100"/>
   <frame tileid="581" duration="100"/>
   <frame tileid="579" duration="100"/>
   <frame tileid="577" duration="100"/>
  </animation>
 </tile>
 <tile id="578" type="Block"/>
 <tile id="579" type="Block"/>
 <tile id="580" type="Block"/>
 <tile id="581" type="Block"/>
 <tile id="582" type="Block"/>
 <tile id="583" type="Block"/>
 <tile id="584" type="Block"/>
 <tile id="585" type="Block"/>
 <tile id="586" type="Block"/>
 <tile id="587" type="Block"/>
 <tile id="588" type="Block"/>
 <tile id="589" type="Block"/>
 <tile id="590" type="Block"/>
 <tile id="591" type="Block"/>
 <tile id="592" type="Block"/>
 <tile id="593" type="Block"/>
 <tile id="594" type="Block"/>
 <tile id="595" type="Block"/>
 <tile id="596" type="Block"/>
 <tile id="597" type="Block"/>
 <tile id="598" type="Block"/>
 <tile id="599" type="Block"/>
 <tile id="600" type="AnimationBlock">
  <properties>
   <property name="animation_id" value="newton_cradle_end"/>
  </properties>
  <animation>
   <frame tileid="600" duration="100"/>
   <frame tileid="602" duration="100"/>
   <frame tileid="604" duration="100"/>
   <frame tileid="606" duration="100"/>
   <frame tileid="608" duration="100"/>
   <frame tileid="606" duration="100"/>
   <frame tileid="604" duration="100"/>
   <frame tileid="602" duration="100"/>
   <frame tileid="600" duration="100"/>
  </animation>
 </tile>
 <tile id="601" type="AnimationBlock">
  <properties>
   <property name="animation_id" value="newton_cradle_end"/>
  </properties>
  <animation>
   <frame tileid="601" duration="100"/>
   <frame tileid="603" duration="100"/>
   <frame tileid="605" duration="100"/>
   <frame tileid="607" duration="100"/>
   <frame tileid="609" duration="100"/>
   <frame tileid="607" duration="100"/>
   <frame tileid="605" duration="100"/>
   <frame tileid="603" duration="100"/>
   <frame tileid="601" duration="100"/>
  </animation>
 </tile>
 <tile id="602" type="Block"/>
 <tile id="603" type="Block"/>
 <tile id="604" type="Block"/>
 <tile id="605" type="Block"/>
 <tile id="606" type="Block"/>
 <tile id="607" type="Block"/>
 <tile id="608" type="Block"/>
 <tile id="609" type="Block"/>
 <tile id="610" type="Block"/>
 <tile id="611" type="Block"/>
 <tile id="612" type="Block"/>
 <tile id="613" type="Block"/>
 <tile id="614" type="Block"/>
 <tile id="615" type="Block"/>
 <tile id="616" type="Block"/>
 <tile id="617" type="Block"/>
 <tile id="618" type="Block"/>
 <tile id="619" type="Block"/>
 <tile id="620" type="Block"/>
 <tile id="621" type="Block"/>
 <tile id="622" type="Block"/>
 <tile id="623" type="Block"/>
 <tile id="624" type="AnimationBlock">
  <properties>
   <property name="animation_activation">initialTrigger: 1
triggerInterval: 60
frameInterval: 60</property>
   <property name="animation_frame_interval" type="int" value="60"/>
   <property name="animation_id" value="water"/>
   <property name="animation_initial_trigger" type="int" value="1"/>
   <property name="animation_trigger_interval" type="int" value="60"/>
  </properties>
  <animation>
   <frame tileid="624" duration="100"/>
   <frame tileid="625" duration="100"/>
  </animation>
 </tile>
 <tile id="625" type="Block">
  <properties>
   <property name="animation_id" value="water"/>
  </properties>
 </tile>
 <tile id="626" type="Block"/>
 <tile id="627" type="Block"/>
 <tile id="628" type="Block"/>
 <tile id="629" type="Block"/>
 <tile id="630" type="Block"/>
 <tile id="631" type="Block"/>
 <tile id="632" type="Block"/>
 <tile id="633" type="Block"/>
 <tile id="634" type="Block"/>
 <tile id="635" type="Block"/>
 <tile id="636" type="Block"/>
 <tile id="637" type="Block"/>
 <tile id="638" type="Block"/>
 <tile id="639" type="Block"/>
 <tile id="640" type="Block"/>
 <tile id="641" type="Block"/>
 <tile id="642" type="Block"/>
 <tile id="643" type="Block"/>
 <tile id="644" type="Block"/>
 <tile id="645" type="Block"/>
 <tile id="646" type="Block"/>
 <tile id="647" type="Block"/>
 <tile id="648" type="AnimationBlock">
  <properties>
   <property name="animation_id" value="lava_manual"/>
  </properties>
  <animation>
   <frame tileid="648" duration="100"/>
   <frame tileid="650" duration="100"/>
   <frame tileid="652" duration="100"/>
   <frame tileid="654" duration="100"/>
   <frame tileid="656" duration="100"/>
   <frame tileid="658" duration="100"/>
   <frame tileid="660" duration="100"/>
   <frame tileid="662" duration="100"/>
   <frame tileid="664" duration="100"/>
   <frame tileid="666" duration="100"/>
   <frame tileid="668" duration="100"/>
   <frame tileid="670" duration="100"/>
   <frame tileid="672" duration="100"/>
   <frame tileid="674" duration="100"/>
   <frame tileid="676" duration="100"/>
   <frame tileid="678" duration="100"/>
   <frame tileid="676" duration="100"/>
   <frame tileid="674" duration="100"/>
   <frame tileid="672" duration="100"/>
   <frame tileid="670" duration="100"/>
   <frame tileid="668" duration="100"/>
   <frame tileid="666" duration="100"/>
   <frame tileid="664" duration="100"/>
   <frame tileid="662" duration="100"/>
   <frame tileid="660" duration="100"/>
   <frame tileid="658" duration="100"/>
   <frame tileid="656" duration="100"/>
   <frame tileid="654" duration="100"/>
   <frame tileid="652" duration="100"/>
   <frame tileid="650" duration="100"/>
   <frame tileid="648" duration="100"/>
  </animation>
 </tile>
 <tile id="649" type="AnimationBlock">
  <properties>
   <property name="animation_id" value="lava_manual"/>
  </properties>
  <animation>
   <frame tileid="649" duration="100"/>
   <frame tileid="651" duration="100"/>
   <frame tileid="653" duration="100"/>
   <frame tileid="655" duration="100"/>
   <frame tileid="657" duration="100"/>
   <frame tileid="659" duration="100"/>
   <frame tileid="661" duration="100"/>
   <frame tileid="663" duration="100"/>
   <frame tileid="665" duration="100"/>
   <frame tileid="667" duration="100"/>
   <frame tileid="669" duration="100"/>
   <frame tileid="671" duration="100"/>
   <frame tileid="673" duration="100"/>
   <frame tileid="675" duration="100"/>
   <frame tileid="677" duration="100"/>
   <frame tileid="679" duration="100"/>
   <frame tileid="677" duration="100"/>
   <frame tileid="675" duration="100"/>
   <frame tileid="673" duration="100"/>
   <frame tileid="671" duration="100"/>
   <frame tileid="669" duration="100"/>
   <frame tileid="667" duration="100"/>
   <frame tileid="665" duration="100"/>
   <frame tileid="663" duration="100"/>
   <frame tileid="661" duration="100"/>
   <frame tileid="659" duration="100"/>
   <frame tileid="657" duration="100"/>
   <frame tileid="655" duration="100"/>
   <frame tileid="653" duration="100"/>
   <frame tileid="651" duration="100"/>
   <frame tileid="649" duration="100"/>
  </animation>
 </tile>
 <tile id="650" type="Block"/>
 <tile id="651" type="Block"/>
 <tile id="652" type="Block"/>
 <tile id="653" type="Block"/>
 <tile id="654" type="Block"/>
 <tile id="655" type="Block"/>
 <tile id="656" type="Block"/>
 <tile id="657" type="Block"/>
 <tile id="658" type="Block"/>
 <tile id="659" type="Block"/>
 <tile id="660" type="Block"/>
 <tile id="661" type="Block"/>
 <tile id="662" type="Block"/>
 <tile id="663" type="Block"/>
 <tile id="664" type="Block"/>
 <tile id="665" type="Block"/>
 <tile id="666" type="Block"/>
 <tile id="667" type="Block"/>
 <tile id="668" type="Block"/>
 <tile id="669" type="Block"/>
 <tile id="670" type="Block"/>
 <tile id="671" type="Block"/>
 <tile id="672" type="Block"/>
 <tile id="673" type="Block"/>
 <tile id="674" type="Block"/>
 <tile id="675" type="Block"/>
 <tile id="676" type="Block"/>
 <tile id="677" type="Block"/>
 <tile id="678" type="Block"/>
 <tile id="679" type="Block"/>
 <tile id="680" type="Block"/>
 <tile id="681" type="Block"/>
 <tile id="682" type="Block"/>
 <tile id="683" type="Block"/>
 <tile id="684" type="Block"/>
 <tile id="685" type="Block"/>
 <tile id="686" type="Block"/>
 <tile id="687" type="Block"/>
 <tile id="688" type="Block"/>
 <tile id="689" type="Block"/>
 <tile id="690" type="Block"/>
 <tile id="691" type="Block"/>
 <tile id="692" type="Block"/>
 <tile id="693" type="Block"/>
 <tile id="694" type="Block"/>
 <tile id="695" type="Block"/>
 <tile id="696" type="Block"/>
 <tile id="697" type="Block"/>
 <tile id="698" type="Block"/>
 <tile id="699" type="Block"/>
 <tile id="700" type="Block"/>
 <tile id="701" type="Block"/>
 <tile id="702" type="Block"/>
 <tile id="703" type="Block"/>
 <tile id="704" type="Block"/>
 <tile id="705" type="Block"/>
 <tile id="706" type="Block"/>
 <tile id="707" type="Block"/>
 <tile id="708" type="Block"/>
 <tile id="709" type="Block"/>
 <tile id="710" type="Block"/>
 <tile id="711" type="Block"/>
 <tile id="712" type="Block"/>
 <tile id="713" type="Block"/>
 <tile id="714" type="Block"/>
 <tile id="715" type="Block"/>
 <tile id="716" type="Block"/>
 <tile id="717" type="Block"/>
 <tile id="718" type="Block"/>
 <tile id="719" type="Block"/>
 <tile id="720" type="Block"/>
 <tile id="721" type="Block"/>
 <tile id="722" type="Block"/>
 <tile id="723" type="Block"/>
 <tile id="724" type="Block"/>
 <tile id="725" type="Block"/>
 <tile id="726" type="Block"/>
 <tile id="727" type="Block"/>
 <tile id="728" type="Block"/>
 <tile id="729" type="Block"/>
 <tile id="730" type="Block"/>
 <tile id="731" type="Block"/>
 <tile id="732" type="Block"/>
 <tile id="733" type="Block"/>
 <tile id="734" type="Block"/>
 <tile id="735" type="Block"/>
 <tile id="736" type="Block"/>
 <tile id="737" type="Block"/>
 <tile id="738" type="Block"/>
 <tile id="739" type="Block"/>
 <tile id="740" type="Block"/>
 <tile id="741" type="Block"/>
 <tile id="742" type="Block"/>
 <tile id="743" type="Block"/>
 <tile id="744" type="Block"/>
 <tile id="745" type="Block"/>
 <tile id="746" type="Block"/>
 <tile id="747" type="Block"/>
 <tile id="748" type="Block"/>
 <tile id="749" type="Block"/>
 <tile id="750" type="Block"/>
 <tile id="751" type="Block"/>
 <tile id="752" type="Block"/>
 <tile id="753" type="Block"/>
 <tile id="754" type="Block"/>
 <tile id="755" type="Block"/>
 <tile id="756" type="Block"/>
 <tile id="757" type="Block"/>
 <tile id="758" type="Block"/>
 <tile id="759" type="Block"/>
 <tile id="760" type="Block"/>
 <tile id="761" type="Block"/>
 <tile id="762" type="Block"/>
 <tile id="763" type="Block"/>
 <tile id="764" type="Block"/>
 <tile id="765" type="Block"/>
 <tile id="766" type="Block"/>
 <tile id="767" type="Block"/>
 <tile id="768" type="Block"/>
 <tile id="769" type="Block"/>
 <tile id="770" type="Block"/>
 <tile id="771" type="Block"/>
 <tile id="772" type="Block"/>
 <tile id="773" type="Block"/>
 <tile id="774" type="Block"/>
 <tile id="775" type="Block"/>
 <tile id="776" type="Block"/>
 <tile id="777" type="Block"/>
 <tile id="778" type="Block"/>
 <tile id="779" type="Block"/>
 <tile id="780" type="Block"/>
 <tile id="781" type="Block"/>
 <tile id="782" type="Block"/>
 <tile id="783" type="Block"/>
 <tile id="784" type="Block"/>
 <tile id="785" type="Block"/>
 <tile id="786" type="Block"/>
 <tile id="787" type="Block"/>
 <tile id="788" type="Block"/>
 <tile id="789" type="Block"/>
 <tile id="790" type="Block"/>
 <tile id="791" type="Block"/>
 <tile id="792" type="Block"/>
 <tile id="793" type="Block"/>
 <tile id="794" type="Block"/>
 <tile id="795" type="Block"/>
 <tile id="796" type="Block"/>
 <tile id="797" type="Block"/>
 <tile id="798" type="Block"/>
 <tile id="799" type="Block"/>
 <tile id="800" type="Block"/>
 <tile id="801" type="Block"/>
 <tile id="802" type="Block"/>
 <tile id="803" type="Block"/>
 <tile id="804" type="Block"/>
 <tile id="805" type="Block"/>
 <tile id="806" type="Block"/>
 <tile id="807" type="Block"/>
 <tile id="808" type="Block"/>
 <tile id="809" type="Block"/>
 <tile id="810" type="Block"/>
 <tile id="811" type="Block"/>
 <tile id="812" type="Block"/>
 <tile id="813" type="Block"/>
 <tile id="814" type="Block"/>
 <tile id="815" type="Block"/>
 <tile id="816" type="Block"/>
 <tile id="817" type="Block"/>
 <tile id="818" type="Block"/>
 <tile id="819" type="Block"/>
 <tile id="820" type="Block"/>
 <tile id="821" type="Block"/>
 <tile id="822" type="Block"/>
 <tile id="823" type="Block"/>
 <tile id="824" type="Block"/>
 <tile id="825" type="Block"/>
 <tile id="826" type="Block"/>
 <tile id="827" type="Block"/>
 <tile id="828" type="Block"/>
 <tile id="829" type="Block"/>
 <tile id="830" type="Block"/>
 <tile id="831" type="Block"/>
 <tile id="832" type="Block"/>
 <tile id="833" type="Block"/>
 <tile id="834" type="Block"/>
 <tile id="835" type="Block"/>
 <tile id="836" type="Block"/>
 <tile id="837" type="Block"/>
 <tile id="838" type="Block"/>
 <tile id="839" type="Block"/>
 <tile id="840" type="Block"/>
 <tile id="841" type="Block"/>
 <tile id="842" type="Block"/>
 <tile id="843" type="Block"/>
 <tile id="844" type="Block"/>
 <tile id="845" type="Block"/>
 <tile id="846" type="Block"/>
 <tile id="847" type="Block"/>
 <tile id="848" type="Block"/>
 <tile id="849" type="Block"/>
 <tile id="850" type="Block"/>
 <tile id="851" type="Block"/>
 <tile id="852" type="Block"/>
 <tile id="853" type="Block"/>
 <tile id="854" type="Block"/>
 <tile id="855" type="Block"/>
 <tile id="856" type="Block"/>
 <tile id="857" type="Block"/>
 <tile id="858" type="Block"/>
 <tile id="859" type="Block"/>
 <tile id="860" type="Block"/>
 <tile id="861" type="Block"/>
 <tile id="862" type="Block"/>
 <tile id="863" type="Block"/>
 <tile id="864" type="Block"/>
 <tile id="865" type="Block"/>
 <tile id="866" type="Block"/>
 <tile id="867" type="Block"/>
 <tile id="868" type="Block"/>
 <tile id="869" type="Block"/>
 <tile id="870" type="Block"/>
 <tile id="871" type="Block"/>
 <tile id="872" type="Block"/>
 <tile id="873" type="Block"/>
 <tile id="874" type="Block"/>
 <tile id="875" type="Block"/>
 <tile id="876" type="Block"/>
 <tile id="877" type="Block"/>
 <tile id="878" type="Block"/>
 <tile id="879" type="Block"/>
 <tile id="880" type="Block"/>
 <tile id="881" type="Block"/>
 <tile id="882" type="Block"/>
 <tile id="883" type="Block"/>
 <tile id="884" type="Block"/>
 <tile id="885" type="Block"/>
 <tile id="886" type="Block"/>
 <tile id="887" type="Block"/>
 <tile id="888" type="Block"/>
 <tile id="889" type="Block"/>
 <tile id="890" type="Block"/>
 <tile id="891" type="Block"/>
 <tile id="892" type="Block"/>
 <tile id="893" type="Block"/>
 <tile id="894" type="Block"/>
 <tile id="895" type="Block"/>
 <tile id="896" type="Block"/>
 <tile id="897" type="Block"/>
 <tile id="898" type="Block"/>
 <tile id="899" type="Block"/>
 <tile id="900" type="Block"/>
 <tile id="901" type="Block"/>
 <tile id="902" type="Block"/>
 <tile id="903" type="Block"/>
 <tile id="904" type="Block"/>
 <tile id="905" type="Block"/>
 <tile id="906" type="Block"/>
 <tile id="907" type="Block"/>
 <tile id="908" type="Block"/>
 <tile id="909" type="Block"/>
 <tile id="910" type="Block"/>
 <tile id="911" type="Block"/>
 <tile id="912" type="Block"/>
 <tile id="913" type="Block"/>
 <tile id="914" type="Block"/>
 <tile id="915" type="Block"/>
 <tile id="916" type="Block"/>
 <tile id="917" type="Block"/>
 <tile id="918" type="Block"/>
 <tile id="919" type="Block"/>
 <tile id="920" type="Block"/>
 <tile id="921" type="Block"/>
 <tile id="922" type="Block"/>
 <tile id="923" type="Block"/>
 <tile id="924" type="Block"/>
 <tile id="925" type="Block"/>
 <tile id="926" type="Block"/>
 <tile id="927" type="Block"/>
 <tile id="928" type="Block"/>
 <tile id="929" type="Block"/>
 <tile id="930" type="Block"/>
 <tile id="931" type="Block"/>
 <tile id="932" type="Block"/>
 <tile id="933" type="Block"/>
 <tile id="934" type="Block"/>
 <tile id="935" type="Block"/>
 <tile id="936" type="Block"/>
 <tile id="937" type="Block"/>
 <tile id="938" type="Block"/>
 <tile id="939" type="Block"/>
 <tile id="940" type="Block"/>
 <tile id="941" type="Block"/>
 <tile id="942" type="Block"/>
 <tile id="943" type="Block"/>
 <tile id="944" type="Block"/>
 <tile id="945" type="Block"/>
 <tile id="946" type="Block"/>
 <tile id="947" type="Block"/>
 <tile id="948" type="Block"/>
 <tile id="949" type="Block"/>
 <tile id="950" type="Block"/>
 <tile id="951" type="Block"/>
 <tile id="952" type="Block"/>
 <tile id="953" type="Block"/>
 <tile id="954" type="Block"/>
 <tile id="955" type="Block"/>
 <tile id="956" type="Block"/>
 <tile id="957" type="Block"/>
 <tile id="958" type="Block"/>
 <tile id="959" type="Block"/>
 <tile id="960" type="Block"/>
 <tile id="961" type="Block"/>
 <tile id="962" type="Block"/>
 <tile id="963" type="Block"/>
 <tile id="964" type="Block"/>
 <tile id="965" type="Block"/>
 <tile id="966" type="Block"/>
 <tile id="967" type="Block"/>
 <tile id="968" type="Block"/>
 <tile id="969" type="Block"/>
 <tile id="970" type="Block"/>
 <tile id="971" type="Block"/>
 <tile id="972" type="Block"/>
 <tile id="973" type="Block"/>
 <tile id="974" type="Block"/>
 <tile id="975" type="Block"/>
 <tile id="976" type="Block"/>
 <tile id="977" type="Block"/>
 <tile id="978" type="Block"/>
 <tile id="979" type="Block"/>
 <tile id="980" type="Block"/>
 <tile id="981" type="Block"/>
 <tile id="982" type="Block"/>
 <tile id="983" type="Block"/>
</tileset>
